[Packages]
  GuiApps = [
    "emacs-gtk3",
    "filelight",
    "flameshot",
    "lutris",
    "lxappearance",
    "NoiseTorch",
    "keepassxc",
  ]

  Tools = []

  CliTools = [
    "zoxide",
    "tldr",
  ]

  CliApps = [
    "neofetch",
    "neovim",
    "bpytop",
    "lf",
    "gocryptfs"
  ]

  Wayland = [
    "sway",
    "swayidle",
    "swaylock",
    "dmenu",
    "Waybar",

    "wl-clipboard",
    "xdg-desktop-portal",
    "xdg-desktop-portal-gtk",
    "xdg-desktop-portal-wlr",
    "qt5-wayland",
  ]

  Development = [
    "git",

    "go",

    "zig",

    "make",
    "shellcheck",
  ]

  System = [
    "NetworkManager-openvpn",
  ]

  Preinstalled = [
    "ImageMagick-7.1.0.48_2",
    "base-system-0.114_1",
    "bpytop-1.0.68_1",
    "btrfs-progs-5.19.1_1",
    "cmake-3.24.2_1",
    "cryptsetup-2.4.3_1",
    "curl-7.84.0_2",
    "editorconfig-0.12.4_1",
    "elogind-246.10_2",
    "fd-8.4.0_1",
    "font-awesome-4.7.0_3",
    "foot-1.13.1_1",
    "fzf-0.33.0_1",
    "gcc-10.2.1pre1_3",
    "glib-devel-2.74.0_2",
    "grub-x86_64-efi-2.06_2",
    "gvfs-1.50.2_1",
    "intel-ucode-20220809_1",
    "kwayland-5.97.0_1",
    "libdrm-32bit-2.4.113_1",
    "libgcc-32bit-10.2.1pre1_3",
    "libglvnd-32bit-1.4.0_1",
    "libjack-pipewire-0.3.58_1",
    "libstdc++-32bit-10.2.1pre1_3",
    "libtool-2.4.6_6",
    "mesa-dri-22.1.7_1",
    "mesa-dri-32bit-22.1.7_1",
    "meson-0.63.2_1",
    "nerd-fonts-2.2.2_1",
    "network-manager-applet-1.28.0_1",
    "nix-2.11.0_1",
    "ntp-4.2.8p15_5",
    "obs-28.0.2_1",
    "pamixer-1.6_1",
    "pcmanfm-1.3.2_2",
    "pipewire-0.3.58_1",
    "polkit-121_1",
    "remmina-1.4.27_1",
    "ripgrep-13.0.0_1",
    "rsync-3.2.6_1",
    "sbcl-2.2.9_1",
    "steam-1.0.0.75_2",
    "vala-0.56.3_1",
    "void-repo-multilib-6_4",
    "void-repo-multilib-nonfree-6_4",
    "void-repo-nonfree-9_6",
    "xdg-user-dirs-0.18_1",
    "xdg-user-dirs-gtk-0.10_4",
    "xorg-fonts-7.6_5",
    "xorg-minimal-1.2_2",
    "zsh-5.9_1"
  ]
