[Packages]
  [Packages.paru]
    Apps = [
      "cinny-desktop-bin",
      "discord",
      "telegram-desktop",
      "safeeyes",

      "virtualbox",
      "virtualbox-guest-iso",
      "virtualbox-host-dkms",
    ]

    GuiTools = [
      "ark",
      "aseprite",
      "zathura-pdf-mupdf",
      "wine-staging",

      "thunar",
      "thunar-volman",
    ]

    CliTools = [
      "acpi",     # Battery thing
      "autoconf", # Do I need this?
      "bpytop",
      "bore",
      "tldr",
      "wget",
      "tmux",
      "which",
      "neofetch"
    ]

    System = [
      "archlinux-keyring",
      "base",
      "zsh",
      "zoxide",
      "xorg-server",
      "xorg-xinit",
    ]

    WMs = [
      "sddm",

      "dmenu",
      "wofi",
      "dunst",

      "awesome",

      "sway",
      "swayidle",
      "swaylock",
    ]

    Coding = [
      "code",
      "shellcheck",

      "clj-kondo-bin",
      "clojure",
      "clojure-lsp-bin",
    ]

    Fonts = [
      "adobe-source-han-sans-cn-fonts",
      "adobe-source-han-sans-jp-fonts",
      "adobe-source-han-sans-kr-fonts",
      "adobe-source-han-sans-tw-fonts",
      "adobe-source-han-serif-jp-fonts",
      "ttc-iosevka",
      "ttf-comfortaa",
      "ttf-croscore",
      "ttf-fira-mono",
      "ttf-inconsolata",
      "ttf-jetbrains-mono",
      "ttf-roboto",
      "ttf-sazanami",
      "ttf-ubuntu-font-family",
    ]

    Unsorted = [
      "alsa-firmware",
      "amd-ucode",
      "arm-none-eabi-binutils",
      "arm-none-eabi-gcc",
      "arm-none-eabi-newlib",
      "automake",
      "avr-binutils",
      "avr-gcc",
      "avr-libc",
      "avrdude",
      "binutils",
      "bison",
      "bluez-utils",
      "btrfs-progs",
      "chromium",
      "clang",
      "cmake",
      "cryptomator-bin",
      "debugedit",
      "dfu-programmer",
      "dfu-util",
      "discord-screenaudio",
      "docker",
      "dolphin",
      "dotnet-runtime-6.0",
      "efibootmgr",
      "egl-wayland",
      "element-desktop",
      "emacs",
      "emacs-slime",
      "exodus",
      "fakeroot",
      "fd",
      "file",
      "filelight",
      "findutils",
      "firefox",
      "flameshot",
      "flex",
      "freerdp",
      "gawk",
      "gcc",
      "gettext",
      "gimp",
      "git",
      "go",
      "gocryptfs",
      "grep",
      "grim",
      "groff",
      "gst-plugin-pipewire",
      "gwenview",
      "gzip",
      "huawei-wmi",
      "huawei-wmi-dkms",
      "hunspell-en_us",
      "hunspell-ru",
      "hyprland-bin",
      "i3lock-color",
      "intellij-idea-community-edition",
      "iwd",
      "j4-dmenu-desktop",
      "jetbrains-fleet",
      "jre-openjdk-headless",
      "kate",
      "kdeconnect",
      "kdenlive",
      "keepassxc",
      "kemai",
      "kitty",
      "konsole",
      "krita",
      "kubo",
      "lagrange",
      "languagetool",
      "lapce-nightly-bin",
      "leiningen",
      "lib32-giflib",
      "lib32-gnutls",
      "lib32-gst-plugins-base-libs",
      "lib32-gtk3",
      "lib32-libjpeg-turbo",
      "lib32-libpng",
      "lib32-libpulse",
      "lib32-libva",
      "lib32-libxcomposite",
      "lib32-libxinerama",
      "lib32-libxslt",
      "lib32-mpg123",
      "lib32-ocl-icd",
      "lib32-openal",
      "lib32-v4l-utils",
      "libpulse",
      "libreoffice-fresh",
      "libtool",
      "libva-mesa-driver",
      "linux",
      "linux-firmware",
      "linux-zen",
      "linux-zen-headers",
      "lutris",
      "m4",
      "maim",
      "make",
      "mandoc",
      "mariadb",
      "matebook-applet",
      "meld",
      "meson",
      "micro",
      "mkinitcpio-firmware",
      "monero-gui",
      "moonlight-qt",
      "mpg123",
      "mpv",
      "nano",
      "neovim",
      "nerd-fonts-jetbrains-mono",
      "network-manager-applet",
      "networkmanager",
      "networkmanager-openvpn",
      "ngrok",
      "nheko",
      "ninja",
      "nomachine",
      "noto-fonts-cjk",
      "noto-fonts-emoji",
      "noto-fonts-extra",
      "nuclear-player-bin",
      "obinskit",
      "obs-studio",
      "opentabletdriver",
      "org-protocol-emacsclient",
      "otf-ipafont",
      "pacman",
      "pamac-aur",
      "pamixer",
      "paru",
      "pasystray",
      "patch",
      "pavucontrol-qt",
      "picom",
      "pipewire",
      "pipewire-alsa",
      "pipewire-jack",
      "pipewire-pulse",
      "pkgconf",
      "plasma-meta",
      "plasma-wayland-session",
      "postgresql",
      "python-pip",
      "python-virtualenv",
      "qbittorrent",
      "qmk",
      "qpwgraph",
      "quicklisp",
      "rate-mirrors-bin",
      "redis",
      "remmina",
      "ripgrep",
      "rsync",
      "rustdesk-bin",
      "samba",
      "sbcl",
      "sct",
      "sed",
      "slurp",
      "smartmontools",
      "sof-firmware",
      "steam",
      "stow",
      "sudo",
      "syncthing",
      "texinfo",
      "tlp-rdw",
      "tlpui-git",
      "tor-browser",
      "vulkan-radeon",
      "wavemon",
      "waybar-hyprland-git",
      "wireless_tools",
      "wireplumber",
      "wl-clipboard",
      "xclip",
      "xcolor",
      "xdg-desktop-portal",
      "xdg-utils",
      "xf86-video-amdgpu",
      "xf86-video-ati",
      "zram-generator",
    ]
