[Packages]
  [Packages.paru]
    Apps = [
      "cinny-desktop-bin",
      "element-desktop",
      "nheko",
      "discord",
      "discord-screenaudio",
      "telegram-desktop",
      "lagrange",            # Gemini client
      "nuclear-player-bin",

      "chromium",
      "firefox",
      "tor-browser",

      "steam",
      "lutris",
      "cryptomator-bin",
      "safeeyes",
      "exodus",
      "monero-gui",

      "remmina",
      "nomachine",
      "freerdp",
      "rustdesk-bin",
      "kdeconnect",
      "activate-linux-git",
    ]

    GuiTools = [
      "ark",
      "mpv",
      "gwenview",
      "aseprite",
      "zathura-pdf-mupdf",
      "flameshot",
      "pamac-aur",
      "qpwgraph",

      "virtualbox",
      "virtualbox-guest-iso",
      "virtualbox-host-dkms",

      "gimp",
      "krita",
      "kdenlive",
      "libreoffice-fresh",
      "obs-studio",

      "thunar-extended",
      "thunar-volman",
      "gvfs",
      "tumbler",
      "ffmpegthumbnailer",
      
      "dolphin",
      "filelight",
      "syncthing",

      "qbittorrent",
      "keepassxc",

      "obinskit",  # Keyboard
    ]

    CliTools = [
      "acpi",     # Battery thing
      "autoconf", # Do I need this?
      "bpytop",
      "bore",
      "tldr",
      "wget",
      "tmux",
      "which",
      "neofetch",
      "gocryptfs",
      "kubo",     # IPFS implementation in Go
      "ngrok",
      "pamixer",
      "qmk",      # Keyboard
      "rate-mirrors-bin",
      "rsync",
      "sed",
      "stow",     # Config syncer
      "wavemon",
    ]

    WMs = [
      "sddm",

      "network-manager-applet",
      "pasystray",
      "pavucontrol-qt",

      "dmenu",
      "j4-dmenu-desktop",
      "wofi",
      "dunst",

      "xdg-desktop-portal",
      "xdg-utils",
      # Xorg
      "xorg-server",
      "xorg-xinit",
      "xorg-xkill",
      "picom",
      "maim",       # Screenshot utility
      "sct",        # Color temperature
      "xclip",
      "xcolor",

      "awesome",
      "i3lock-color",

      "leftwm",

      # Wayland
      "wl-clipboard",
      "egl-wayland",
      "grim",
      "slurp",

      "sway",
      "swayidle",
      "swaylock",

      "hyprland-bin",
      "waybar-hyprland-git",

      "plasma-meta",
      "plasma-wayland-session",

      # Gtk settings
      "lxappearance",

      # Qt settings
      "qt5ct",
    ]

    Develop = [
      "neovim",
      "code",
      "kate",
      "lapce-nightly-bin",
      "intellij-idea-community-edition",
      "jetbrains-fleet",
      "meld",

      "emacs",
      "fd",
      "ripgrep",
      "hunspell-en_us",
      "hunspell-ru",
      "languagetool",
      "org-protocol-emacsclient",

      "docker",
      "shellcheck",

      "emacs-slime", # For lisp
      "quicklisp",
      "sbcl",

      "go",

      "jre-openjdk-headless",
      "clj-kondo-bin",
      "clojure",
      "clojure-lsp-bin",
      "leiningen",

      "gcc",
      "automake",
      "make",
      "cmake",
      "meson",
      "ninja",
      "bison",
      "clang",
      "dfu-programmer",
      "dfu-util",

      "dotnet-runtime-6.0",

      "python-pip",
      "python-virtualenv",

      "mongodb-compass",
    ]

    System = [
      "linux-zen",
      "linux-zen-headers",
      "mkinitcpio-firmware", # kernal warnings

      "vulkan-radeon",
      "xf86-video-amdgpu",
      "xf86-video-ati",

      "zsh",
      "zoxide",
      "git",
      "paru",

      "kitty",
      "konsole",
      "opentabletdriver",
      "samba",

      "matebook-applet",
      "huawei-wmi",
      "huawei-wmi-dkms",

      "networkmanager-openvpn",
      "sof-firmware",
    ]

    Wine = [
      "wine-staging",
      "mpg123",
      "lib32-giflib",
      "lib32-gnutls",
      "lib32-gst-plugins-base-libs",
      "lib32-gtk3",
      "lib32-libjpeg-turbo",
      "lib32-libpng",
      "lib32-libva",
      "lib32-libxcomposite",
      "lib32-libxinerama",
      "lib32-libxslt",
      "lib32-mpg123",
      "lib32-ocl-icd",
      "lib32-openal",
      "lib32-v4l-utils",
    ]

    BaseSystem = [
      "linux",
      "linux-firmware",
      "zram-generator",

      "networkmanager",
      "wireless_tools",

      "archlinux-keyring",
      "base",
      "patch",
      "gettext",
      "flex",
      "binutils",
      "debugedit",
      "file",
      "sudo",
      "fakeroot",
      "pacman",
      "findutils",
      "gawk",
      "grep",
      "groff",
      "gzip",
      "iwd",
      "libtool",
      "m4",
      "mandoc",
      "pkgconf",
      "texinfo",

      "alsa-firmware",
      "bluez-utils",
      "btrfs-progs",
      "efibootmgr",

      "amd-ucode",
      "arm-none-eabi-binutils",
      "arm-none-eabi-gcc",
      "arm-none-eabi-newlib",
      "avr-binutils",
      "avr-gcc",
      "avr-libc",
      "avrdude",

      "libva-mesa-driver",

      # Sound
      "pipewire",
      "pipewire-alsa",
      "pipewire-jack",
      "pipewire-pulse",
      "lib32-libpulse",
      "gst-plugin-pipewire",
      "libpulse",
      "wireplumber",

      # Power
      "smartmontools",
      "tlp-rdw",
      "tlpui-git",
    ]

    Fonts = [
      "nerd-fonts-jetbrains-mono",
      "adobe-source-han-sans-cn-fonts",
      "adobe-source-han-sans-jp-fonts",
      "adobe-source-han-sans-kr-fonts",
      "adobe-source-han-sans-tw-fonts",
      "adobe-source-han-serif-jp-fonts",
      "ttc-iosevka",
      "ttf-comfortaa",
      "ttf-croscore",
      "ttf-fira-mono",
      "ttf-inconsolata",
      "ttf-jetbrains-mono",
      "ttf-roboto",
      "ttf-sazanami",
      "ttf-ubuntu-font-family",
      "noto-fonts-cjk",
      "noto-fonts-emoji",
      "noto-fonts-extra",
      "otf-ipafont",
    ]
